'use strict';

var props_array =
[ { _id: '7',
    'episode number': 7,
    'publish date': '2016-02-10 8',
    'book title': 'The Statement Of Randolph Carter',
    'book author': 'H.P. Lovecraft',
    'story link on wikipedia': 'http://en.wikipedia.org/wiki/The_Statement_of_Randolph_Carter',
    'author wikipedia entry': '',
    'pdf link 1': 'http://www.sffaudio.com/podcasts/TheStatementOfRandolphCarterByHPLovecraft.pdf',
    'pdf page count 1': 6,
    'pdf country 1': '',
    'pdf info 1': '',
    'pdf link 2': 'http://www.sffaudio.com/podcasts/TheStatementOfRandolphCarterWEIRDTALES.pdf',
    'pdf page count 2': 5,
    'pdf country 2': '',
    'pdf info 2': '',
    'pdf link 3': 'http://www.sffaudio.com/podcasts/TheStatementOfRandolphCarterByH.P.Lovecraftb.pdf',
    'pdf page count 3': 6,
    'pdf country 3': '',
    'pdf info 3': '',
    'pdf link 4': 'http://www.sffaudio.com/podcasts/TheStatementOfRandolphCarterByH.P.LovecraftWTAug1937.pdf',
    'pdf page count 4': 6,
    'pdf country 4': '',
    'pdf info 4': 'Weird Tales, August 1937',
    real_or_test: 'real',
    __v: 0 },
  { _id: '6',
    'episode number': 6,
    'publish date': '2016-06-24 20',
    'book title': 'The Scandal Detectives',
    'book author': 'F. Scott Fitzgerald',
    'story link on wikipedia': '',
    'author wikipedia entry': 'https://en.wikipedia.org/wiki/F._Scott_Fitzgerald',
    'pdf link 1': 'http://www.coquitlamwebsolutions.ca/sffaudio_can_pdfs/TheScandalDetectivesByF.ScottFitzgerald.pdf',
    'pdf page count 1': 20,
    'pdf country 1': 'Canada',
    'pdf info 1': 'Alfred Hitchcock\'s Mystery Magazine, April 1991',
    real_or_test: 'real',
    __v: 0 },
  { _id: '5',
    'episode number': 5,
    'publish date': '2016-06-21 13',
    'book title': 'Scaramouche',
    'book author': 'Rafael Sabatini',
    'story link on wikipedia': 'https://en.wikipedia.org/wiki/Scaramouche_(novel)',
    'author wikipedia entry': 'https://en.wikipedia.org/wiki/Rafael_Sabatini',
    'pdf link 1': 'http://www.sffaudio.com/podcasts/ScaramoucheByRafaelSabatiniFAI13.pdf',
    'pdf page count 1': 31,
    'pdf country 1': '',
    'pdf info 1': 'Famous Authors Illustrated, No. 13, March 1951',
    'pdf link 2': 'http://www.sffaudio.com/podcasts/ScaramoucheByRafaelSabatini.pdf',
    'pdf page count 2': 398,
    'pdf country 2': '',
    'pdf info 2': 'Houghton Mifflin, 1923',
    real_or_test: 'real',
    __v: 0 },
  { _id: '4',
    'episode number': 4,
    'publish date': '2016-06-23 13',
    'book title': 'Earth Can Be Fun',
    'book author': 'John Jakes',
    'story link on wikipedia': '',
    'author wikipedia entry': 'https://en.wikipedia.org/wiki/John_Jakes',
    'pdf link 1': 'http://www.sffaudio.com/podcasts/EarthCanBeFunByJohnW.Jakes.pdf',
    'pdf page count 1': 16,
    'pdf country 1': '',
    'pdf info 1': 'Imagination, May 1953',
    real_or_test: 'real',
    __v: 0 },
  { _id: '3',
    'episode number': 3,
    'publish date': '2016-06-13 18',
    'book title': 'The Swine Of Ææa',
    'book author': 'Clifford Ball',
    'story link on wikipedia': '',
    'author wikipedia entry': 'https://en.wikipedia.org/wiki/Clifford_Ball',
    'pdf link 1': 'http://www.sffaudio.com/podcasts/TheSwineOfAeaeaByCliffordBall.pdf',
    'pdf page count 1': 28,
    'pdf country 1': '',
    'pdf info 1': 'Weird Tales, March 1939',
    real_or_test: 'real',
    __v: 0 },
  { _id: '2',
    'episode number': 2,
    'publish date': '2016-05-30 13',
    'book title': 'The Case Of Charles Dexter Ward',
    'book author': 'H.P. Lovecraft',
    'story link on wikipedia': 'https://en.wikipedia.org/wiki/The_Case_of_Charles_Dexter_Ward',
    'author wikipedia entry': '',
    'pdf link 1': 'http://www.sffaudio.com/podcasts/TheCaseOfCharlesDexterWardByH.P.Lovecraft.pdf',
    'pdf page count 1': 80,
    'pdf country 1': '',
    'pdf info 1': 'Weird Tales, May and July 1941',
    real_or_test: 'real',
    __v: 0 },
  { _id: '1',
    'episode number': 1,
    'publish date': '2016-02-10 8',
    'book title': 'Worms Of The Earth',
    'book author': 'Robert E. Howard',
    'story link on wikipedia': 'https://en.wikipedia.org/wiki/Worms_of_the_Earth',
    'author wikipedia entry': '',
    'pdf link 1': 'http://www.coquitlamwebsolutions.ca/sffaudio_can_pdfs/WormsOfTheEarthByRobertE.HowardFFM.pdf',
    'pdf page count 1': 14,
    'pdf country 1': 'Canada',
    'pdf info 1': 'Famous Fantastic Mysteries, June 1953',
    'pdf link 2': 'http://www.coquitlamwebsolutions.ca/sffaudio_can_pdfs/WormsOfTheEarthByRobertE.HowardWT2.pdf',
    'pdf page count 2': 21,
    'pdf country 2': 'Canada',
    'pdf info 2': 'Weird Tales, October 1939',
    'pdf link 3': 'http://www.coquitlamwebsolutions.ca/sffaudio_can_pdfs/WormsOfTheEarthByRobertE.HowardWTNov1932.pdf',
    'pdf page count 3': 22,
    'pdf country 3': 'Canada',
    'pdf info 3': 'Weird Tales, November 1932',
    real_or_test: 'real',
    __v: 0 } ];
module.exports = props_array;
