type MediaRows = {mp3_url: String,
    byte_size: String,
    itunes_pubDate: String,
    "episode number": Number,
    "post link": String,
    "file name": String,
    "hh:mm:ss": String,
    "byte size": String,
    "podcast participants": String,
    "book title": String,
    "book author": String,
    "genre type": String,
    "pdf link": String,
    "video link": String,
    "podcast description": String};
