'use strict';


var props_array =
    [
        {
            "_id": "6",
            "episode number": 6,
            "publish date": "2016-03-16 16",
            "post link": "http://www.sffaudio.com/reading-short-and-deep-006-friend-island-by-francis-stevens",
            "file name": "rsd006FriendIsland.mp3",
            "hh:mm:ss": "0:40:10",
            "byte size": "38,811,176",
            "podcast participants": "Eric S. Rabkin and Jesse Willis",
            "book title": "Friend Island",
            "book author": "Francis Stevens",
            "genre type": "Story",
            "pdf link": "http://www.sffaudio.com/podcasts/FriendIslandByFrancisStevens.pdf",
            "video link": "",
            "podcast description": "Friend Island by Francis Stevens",
            "publish_media_now": "yes",
            "itunes_pubDate": "Wed, 16 Mar 2016 16:00:00 PDT",
            "mp3_url": "http://www.canadianquotations.ca/rsd/rsd006FriendIsland.mp3",
            "byte_size": "38811176",
            "real_or_test": "real",
            "__v": 0
        },
        {
            "_id": "5",
            "episode number": 5,
            "publish date": "2016-03-09 00",
            "post link": "http://www.sffaudio.com/reading-short-and-deep-005-the-ancient-track-by-h-p-lovecraft",
            "file name": "rsd005TheAncientTrack.mp3",
            "hh:mm:ss": "0:32:53",
            "byte size": "31,810,320",
            "podcast participants": "Eric S. Rabkin and Jesse Willis",
            "book title": "The Ancient Track",
            "book author": "H.P. Lovecraft",
            "genre type": "Story",
            "pdf link": "http://www.sffaudio.com/podcasts/TheAncientTrackByH.P.LovecraftWEIRDTALESMarch1930.pdf",
            "video link": "",
            "podcast description": "The Ancient Track by H.P. Lovecraft",
            "publish_media_now": "yes",
            "itunes_pubDate": "Wed, 9 Mar 2016 00:00:00 PDT",
            "mp3_url": "http://www.canadianquotations.ca/rsd/rsd005TheAncientTrack.mp3",
            "byte_size": "31810320",
            "real_or_test": "real",
            "__v": 0
        },
        {
            "_id": "4",
            "episode number": 4,
            "publish date": "2016-03-02 00",
            "post link": "http://www.sffaudio.com/reading-short-and-deep-004-the-words-of-guru-by-c-m-kornbluth",
            "file name": "rsd004TheWordsOfGuru.mp3",
            "hh:mm:ss": "0:35:47",
            "byte size": "34,598,565",
            "podcast participants": "Eric S. Rabkin and Jesse Willis",
            "book title": "The Words of Guru",
            "book author": "C.M. Kornbluth",
            "genre type": "Story",
            "pdf link": "http://www.sffaudio.com/podcasts/TheWordsOfGuruByC.M.KornbluthAFR5.pdf",
            "video link": "",
            "podcast description": "The Words of Guru by C.M. Kornbluth",
            "publish_media_now": "yes",
            "itunes_pubDate": "Wed, 2 Mar 2016 00:00:00 PDT",
            "mp3_url": "http://www.canadianquotations.ca/rsd/rsd004TheWordsOfGuru.mp3",
            "byte_size": "34598565",
            "real_or_test": "real",
            "__v": 0
        },
        {
            "_id": "3",
            "episode number": 3,
            "publish date": "2016-02-24 00",
            "post link": "http://www.sffaudio.com/reading-short-and-deep-003-the-flowering-of-the-strange-orchid-by-h-g-wells",
            "file name": "rsd003StrangeOrchid.mp3",
            "hh:mm:ss": "0:26:34",
            "byte size": "25,753,056",
            "podcast participants": "Eric S. Rabkin and Jesse Willis",
            "book title": "The Flowering Of The Strange Orchid",
            "book author": "H.G. Wells",
            "genre type": "Poem",
            "pdf link": "http://www.sffaudio.com/podcasts/TheFloweringOfTheStrangeOrchidByH.G.WellsPEARSONS.pdf",
            "video link": "",
            "podcast description": "The Flowering Of The Strange Orchid by H.G. Wells",
            "publish_media_now": "yes",
            "itunes_pubDate": "Wed, 24 Feb 2016 00:00:00 PDT",
            "mp3_url": "http://www.canadianquotations.ca/rsd/rsd003StrangeOrchid.mp3",
            "byte_size": "25753056",
            "real_or_test": "real",
            "__v": 0
        },
        {
            "_id": "2",
            "episode number": 2,
            "publish date": "2016-02-17 01",
            "post link": "http://www.sffaudio.com/reading-short-and-deep-002-rapunzel-by-the-brothers-grimm",
            "file name": "rsd002Rapunzel.mp3",
            "hh:mm:ss": "0:30:19",
            "byte size": "29,352,408",
            "podcast participants": "Eric S. Rabkin and Jesse Willis",
            "book title": "Rapunzel",
            "book author": "The Brothers Grimm",
            "genre type": "Poem",
            "pdf link": "http://www.sffaudio.com/podcasts/RapunzelByBrosGrimm.pdf",
            "video link": "",
            "podcast description": "Rapunzel by The Brothers Grimm",
            "publish_media_now": "yes",
            "itunes_pubDate": "Wed, 17 Feb 2016 01:00:00 PDT",
            "mp3_url": "http://www.canadianquotations.ca/rsd/rsd002Rapunzel.mp3",
            "byte_size": "29352408",
            "real_or_test": "real",
            "__v": 0
        },
        {
            "_id": "1",
            "episode number": 1,
            "publish date": "2016-02-10 08",
            "post link": "http://www.sffaudio.com/reading-short-and-deep-001-zero-hour-by-ray-bradbury",
            "file name": "rsd001ZeroHour.mp3",
            "hh:mm:ss": "0:34:05",
            "byte size": "32,972,064",
            "podcast participants": "Eric S. Rabkin and Jesse Willis",
            "book title": "Zero Hour",
            "book author": "Ray Bradbury",
            "genre type": "Other",
            "pdf link": "http://www.sffaudio.com/podcasts/ZeroHourByRayBradbury.pdf",
            "video link": "",
            "podcast description": "Zero Hour by Ray Bradbury",
            "publish_media_now": "yes",
            "itunes_pubDate": "Wed, 10 Feb 2016 08:00:00 PDT",
            "mp3_url": "http://www.canadianquotations.ca/rsd/rsd001ZeroHour.mp3",
            "byte_size": "32972064",
            "real_or_test": "real",
            "__v": 0
        }];


module.exports = props_array;