'use strict';


var props_array =
    [{
        "_id": "17",
        "episode number": 17,
        "publish date": "2016-06-01 00",
        "post link": "http://www.sffaudio.com/reading-short-and-deep-017-the-wolf-by-guy-de-maupassant/",
        "file name": "rsd017TheWolf.mp3",
        "hh:mm:ss": "0:30:30",
        "byte size": "29,531,040",
        "podcast participants": "Eric S. Rabkin and Jesse Willis",
        "book title": "The Wolf",
        "book author": "Guy de Maupassant",
        "genre type": "Story",
        "pdf link": "http://www.sffaudio.com/podcasts/TheWolfByGuyDeMaupassant.pdf",
        "video link": "",
        "podcast description": "The Wolf by Guy de Maupassant",
        "publish_media_now": "yes",
        "itunes_pubDate": "Wed, 1 Jun 2016 00:00:00 PDT",
        "mp3_url": "http://www.canadianquotations.ca/rsd/rsd017TheWolf.mp3",
        "byte_size": "29531040",
        "real_or_test": "real",
        "__v": 0
    },
        {
            "_id": "16",
            "episode number": 16,
            "publish date": "2016-05-25 00",
            "post link": "http://www.sffaudio.com/reading-short-and-deep-016-the-house-by-fredric-brown/",
            "file name": "rsd016TheHouse.mp3",
            "hh:mm:ss": "0:29:53",
            "byte size": "28,930,848",
            "podcast participants": "Eric S. Rabkin and Jesse Willis",
            "book title": "The House",
            "book author": "Fredric Brown",
            "genre type": "Poem",
            "pdf link": "http://www.sffaudio.com/podcasts/TheHouseByFredricBrown.pdf",
            "video link": "",
            "podcast description": "The House by Fredric Brown",
            "publish_media_now": "yes",
            "itunes_pubDate": "Wed, 25 May 2016 00:00:00 PDT",
            "mp3_url": "http://www.canadianquotations.ca/rsd/rsd016TheHouse.mp3",
            "byte_size": "28930848",
            "real_or_test": "real",
            "__v": 0
        },
        {
            "_id": "15",
            "episode number": 15,
            "publish date": "2016-05-18 00",
            "post link": "http://www.sffaudio.com/reading-short-and-deep-015-the-mirrors-of-tuzun-thune-by-robert-e-howard/",
            "file name": "rsd015TheMirrorsOfTuzunThune.mp3",
            "hh:mm:ss": "0:35:13",
            "byte size": "34,059,552",
            "podcast participants": "Eric S. Rabkin and Jesse Willis",
            "book title": "The Mirrors of Tuzun Thune",
            "book author": "Robert E. Howard",
            "genre type": "Story",
            "pdf link": "http://www.sffaudio.com/podcasts/TheMirrorsOfTuzunThuneByRobertE.HowardWT.pdf",
            "video link": "",
            "podcast description": "The Mirrors of Tuzun Thune by Robert E. Howard",
            "publish_media_now": "yes",
            "itunes_pubDate": "Wed, 18 May 2016 00:00:00 PDT",
            "mp3_url": "http://www.canadianquotations.ca/rsd/rsd015TheMirrorsOfTuzunThune.mp3",
            "byte_size": "34059552",
            "real_or_test": "real",
            "__v": 0
        },
        {
            "_id": "14",
            "episode number": 14,
            "publish date": "2016-05-11 00",
            "post link": "http://www.sffaudio.com/reading-short-and-deep-014-the-library-of-babel-by-jorge-luis-borges/",
            "file name": "rsd014TheLibraryOfBabel.mp3",
            "hh:mm:ss": "0:50:59",
            "byte size": "49,193,451",
            "podcast participants": "Eric S. Rabkin and Jesse Willis",
            "book title": "The Library of Babel",
            "book author": "Jorge Luis Borges",
            "genre type": "Other",
            "pdf link": "http://www.sffaudio.com/podcasts/TheLibraryOfBabelByJorgeLuisBorges.pdf",
            "video link": "",
            "podcast description": "The Library of Babel by Jorge Luis Borges",
            "publish_media_now": "yes",
            "itunes_pubDate": "Wed, 11 May 2016 00:00:00 PDT",
            "mp3_url": "http://www.canadianquotations.ca/rsd/rsd014TheLibraryOfBabel.mp3",
            "byte_size": "49193451",
            "real_or_test": "real",
            "__v": 0
        },
        {
            "_id": "13",
            "episode number": 13,
            "publish date": "2016-05-04 00",
            "post link": "http://www.sffaudio.com/reading-short-and-deep-013-the-dog-and-the-horse-by-voltaire/",
            "file name": "rsd013TheDogAndTheHorse.mp3",
            "hh:mm:ss": "0:31:22",
            "byte size": "30,352,416",
            "podcast participants": "Eric S. Rabkin and Jesse Willis",
            "book title": "The Dog and the Horse",
            "book author": "Voltaire",
            "genre type": "Poem",
            "pdf link": "",
            "video link": "https://www.youtube.com/watch?v=yc8jjeUr6lE",
            "podcast description": "The Dog and the Horse by Voltaire",
            "publish_media_now": "yes",
            "itunes_pubDate": "Wed, 4 May 2016 00:00:00 PDT",
            "mp3_url": "http://www.canadianquotations.ca/rsd/rsd013TheDogAndTheHorse.mp3",
            "byte_size": "30352416",
            "real_or_test": "real",
            "__v": 0
        },
        {
            "_id": "12",
            "episode number": 12,
            "publish date": "2016-04-27 00",
            "post link": "http://www.sffaudio.com/reading-short-and-deep-012-all-cats-are-gray-by-andre-norton",
            "file name": "rsd012AllCatsAreGray.mp3",
            "hh:mm:ss": "0:32:31",
            "byte size": "31,455,456",
            "podcast participants": "Eric S. Rabkin and Jesse Willis",
            "book title": "All Cats Are Grey",
            "book author": "Andre Norton",
            "genre type": "Story",
            "pdf link": "http://www.sffaudio.com/podcasts/AllCatsAreGrayByAndreNorton.pdf",
            "video link": "",
            "podcast description": "All Cats Are Grey by Andre Norton",
            "publish_media_now": "yes",
            "itunes_pubDate": "Wed, 27 Apr 2016 00:00:00 PDT",
            "mp3_url": "http://www.canadianquotations.ca/rsd/rsd012AllCatsAreGray.mp3",
            "byte_size": "31455456",
            "real_or_test": "real",
            "__v": 0
        },
        {
            "_id": "11",
            "episode number": 11,
            "publish date": "2016-04-20 01",
            "post link": "http://www.sffaudio.com/reading-short-and-deep-011-the-roller-coaster-by-alfred-bester",
            "file name": "rsd011TheRollercoaster.mp3",
            "hh:mm:ss": "0:37:15",
            "byte size": "35,998,944",
            "podcast participants": "Eric S. Rabkin and Jesse Willis",
            "book title": "The Rollercoaster",
            "book author": "Alfred Bester",
            "genre type": "Other",
            "pdf link": "http://www.sffaudio.com/podcasts/TheRollerCoasterByAlfredBester.pdf",
            "video link": "",
            "podcast description": "The Rollercoaster by Alfred Bester",
            "publish_media_now": "yes",
            "itunes_pubDate": "Wed, 20 Apr 2016 01:00:00 PDT",
            "mp3_url": "http://www.canadianquotations.ca/rsd/rsd011TheRollercoaster.mp3",
            "byte_size": "35998944",
            "real_or_test": "real",
            "__v": 0
        },
        {
            "_id": "10",
            "episode number": 10,
            "publish date": "2016-04-13 04",
            "post link": "http://www.sffaudio.com/reading-short-and-deep-010-la-belle-dame-sans-merci-by-john-keats",
            "file name": "rsd010LaBelleDameSansMercy.mp3",
            "hh:mm:ss": "0:30:24",
            "byte size": "29,438,304",
            "podcast participants": "Eric S. Rabkin and Jesse Willis",
            "book title": "La Belle Dame Sans Mercy",
            "book author": "John Keats",
            "genre type": "Poem",
            "pdf link": "http://www.sffaudio.com/podcasts/LaBelleDameSansMercyByJohnKeatsINDICATORMay101820.pdf",
            "video link": "",
            "podcast description": "La Belle Dame sans Mercy by John Keats",
            "publish_media_now": "yes",
            "itunes_pubDate": "Wed, 13 Apr 2016 04:00:00 PDT",
            "mp3_url": "http://www.canadianquotations.ca/rsd/rsd010LaBelleDameSansMercy.mp3",
            "byte_size": "29438304",
            "real_or_test": "real",
            "__v": 0
        },
        {
            "_id": "9",
            "episode number": 9,
            "publish date": "2016-04-06 03",
            "post link": "http://www.sffaudio.com/reading-short-and-deep-009-the-nine-billion-names-of-god-by-sir-arthur-c-clarke",
            "file name": "rsd009NineBillion.mp3",
            "hh:mm:ss": "0:36:13",
            "byte size": "35,007,329",
            "podcast participants": "Eric S. Rabkin and Jesse Willis",
            "book title": "The Nine Billion Names Of God",
            "book author": "Arthur C. Clarke",
            "genre type": "Story",
            "pdf link": "http://www.sffaudio.com/podcasts/TheNineBillionNamesOfGodByArthurC.Clarke.pdf",
            "video link": "",
            "podcast description": "Nine Billion by Arthur C. Clarke",
            "publish_media_now": "yes",
            "itunes_pubDate": "Wed, 6 Apr 2016 03:00:00 PDT",
            "mp3_url": "http://www.canadianquotations.ca/rsd/rsd009NineBillion.mp3",
            "byte_size": "35007329",
            "real_or_test": "real",
            "__v": 0
        },
        {
            "_id": "8",
            "episode number": 8,
            "publish date": "2016-03-30 00",
            "post link": "http://www.sffaudio.com/reading-short-and-deep-008-dream-land-by-edgar-allan-poe",
            "file name": "rsd008Dreamland.mp3",
            "hh:mm:ss": "0:34:01",
            "byte size": "32,909,174",
            "podcast participants": "Eric S. Rabkin and Jesse Willis",
            "book title": "Dream-Land",
            "book author": "Edgar Allan Poe",
            "genre type": "Other",
            "pdf link": "http://www.sffaudio.com/podcasts/DreamLandByEdgarAllanPoeGrahamsLadysAndGentlemansMagazineJune1844.pdf",
            "video link": "",
            "podcast description": "Dreamland by Edgar Allan Poe",
            "publish_media_now": "yes",
            "itunes_pubDate": "Wed, 30 Mar 2016 00:00:00 PDT",
            "mp3_url": "http://www.canadianquotations.ca/rsd/rsd008Dreamland.mp3",
            "byte_size": "32909174",
            "real_or_test": "real",
            "__v": 0
        },
        {
            "_id": "7",
            "episode number": 7,
            "publish date": "2016-03-23 00",
            "post link": "http://www.sffaudio.com/reading-short-and-deep-007-beyond-lies-the-wub-by-philip-k-dick",
            "file name": "rsd007BeyondLiesTheWub.mp3",
            "hh:mm:ss": "0:33:34",
            "byte size": "32,473,243",
            "podcast participants": "Eric S. Rabkin and Jesse Willis",
            "book title": "Beyond Lies The Wub",
            "book author": "Philip K. Dick",
            "genre type": "Poem",
            "pdf link": "http://www.sffaudio.com/podcasts/BeyondLiesTheWubByPhilipK.Dick.pdf",
            "video link": "",
            "podcast description": "Beyond Lies the Wub by Philip K. Dick",
            "publish_media_now": "yes",
            "itunes_pubDate": "Wed, 23 Mar 2016 00:00:00 PDT",
            "mp3_url": "http://www.canadianquotations.ca/rsd/rsd007BeyondLiesTheWub.mp3",
            "byte_size": "32473243",
            "real_or_test": "real",
            "__v": 0
        },
        {
            "_id": "6",
            "episode number": 6,
            "publish date": "2016-03-16 16",
            "post link": "http://www.sffaudio.com/reading-short-and-deep-006-friend-island-by-francis-stevens",
            "file name": "rsd006FriendIsland.mp3",
            "hh:mm:ss": "0:40:10",
            "byte size": "38,811,176",
            "podcast participants": "Eric S. Rabkin and Jesse Willis",
            "book title": "Friend Island",
            "book author": "Francis Stevens",
            "genre type": "Story",
            "pdf link": "http://www.sffaudio.com/podcasts/FriendIslandByFrancisStevens.pdf",
            "video link": "",
            "podcast description": "Friend Island by Francis Stevens",
            "publish_media_now": "yes",
            "itunes_pubDate": "Wed, 16 Mar 2016 16:00:00 PDT",
            "mp3_url": "http://www.canadianquotations.ca/rsd/rsd006FriendIsland.mp3",
            "byte_size": "38811176",
            "real_or_test": "real",
            "__v": 0
        },
        {
            "_id": "5",
            "episode number": 5,
            "publish date": "2016-03-09 00",
            "post link": "http://www.sffaudio.com/reading-short-and-deep-005-the-ancient-track-by-h-p-lovecraft",
            "file name": "rsd005TheAncientTrack.mp3",
            "hh:mm:ss": "0:32:53",
            "byte size": "31,810,320",
            "podcast participants": "Eric S. Rabkin and Jesse Willis",
            "book title": "The Ancient Track",
            "book author": "H.P. Lovecraft",
            "genre type": "Poem",
            "pdf link": "http://www.sffaudio.com/podcasts/TheAncientTrackByH.P.LovecraftWEIRDTALESMarch1930.pdf",
            "video link": "",
            "podcast description": "The Ancient Track by H.P. Lovecraft",
            "publish_media_now": "yes",
            "itunes_pubDate": "Wed, 9 Mar 2016 00:00:00 PDT",
            "mp3_url": "http://www.canadianquotations.ca/rsd/rsd005TheAncientTrack.mp3",
            "byte_size": "31810320",
            "real_or_test": "real",
            "__v": 0
        },
        {
            "_id": "4",
            "episode number": 4,
            "publish date": "2016-03-02 00",
            "post link": "http://www.sffaudio.com/reading-short-and-deep-004-the-words-of-guru-by-c-m-kornbluth",
            "file name": "rsd004TheWordsOfGuru.mp3",
            "hh:mm:ss": "0:35:47",
            "byte size": "34,598,565",
            "podcast participants": "Eric S. Rabkin and Jesse Willis",
            "book title": "The Words of Guru",
            "book author": "C.M. Kornbluth",
            "genre type": "Poem",
            "pdf link": "http://www.sffaudio.com/podcasts/TheWordsOfGuruByC.M.KornbluthAFR5.pdf",
            "video link": "",
            "podcast description": "The Words of Guru by C.M. Kornbluth",
            "publish_media_now": "yes",
            "itunes_pubDate": "Wed, 2 Mar 2016 00:00:00 PDT",
            "mp3_url": "http://www.canadianquotations.ca/rsd/rsd004TheWordsOfGuru.mp3",
            "byte_size": "34598565",
            "real_or_test": "real",
            "__v": 0
        },
        {
            "_id": "3",
            "episode number": 3,
            "publish date": "2016-02-24 00",
            "post link": "http://www.sffaudio.com/reading-short-and-deep-003-the-flowering-of-the-strange-orchid-by-h-g-wells",
            "file name": "rsd003StrangeOrchid.mp3",
            "hh:mm:ss": "0:26:34",
            "byte size": "25,753,056",
            "podcast participants": "Eric S. Rabkin and Jesse Willis",
            "book title": "The Flowering Of The Strange Orchid",
            "book author": "H.G. Wells",
            "genre type": "Story",
            "pdf link": "http://www.sffaudio.com/podcasts/TheFloweringOfTheStrangeOrchidByH.G.WellsPEARSONS.pdf",
            "video link": "",
            "podcast description": "The Flowering Of The Strange Orchid by H.G. Wells",
            "publish_media_now": "yes",
            "itunes_pubDate": "Wed, 24 Feb 2016 00:00:00 PDT",
            "mp3_url": "http://www.canadianquotations.ca/rsd/rsd003StrangeOrchid.mp3",
            "byte_size": "25753056",
            "real_or_test": "real",
            "__v": 0
        },
        {
            "_id": "2",
            "episode number": 2,
            "publish date": "2016-02-17 01",
            "post link": "http://www.sffaudio.com/reading-short-and-deep-002-rapunzel-by-the-brothers-grimm",
            "file name": "rsd002Rapunzel.mp3",
            "hh:mm:ss": "0:30:19",
            "byte size": "29,352,408",
            "podcast participants": "Eric S. Rabkin and Jesse Willis",
            "book title": "Rapunzel",
            "book author": "The Brothers Grimm",
            "genre type": "Other",
            "pdf link": "http://www.sffaudio.com/podcasts/RapunzelByBrosGrimm.pdf",
            "video link": "",
            "podcast description": "Rapunzel by The Brothers Grimm",
            "publish_media_now": "yes",
            "itunes_pubDate": "Wed, 17 Feb 2016 01:00:00 PDT",
            "mp3_url": "http://www.canadianquotations.ca/rsd/rsd002Rapunzel.mp3",
            "byte_size": "29352408",
            "real_or_test": "real",
            "__v": 0
        },
        {
            "_id": "1",
            "episode number": 1,
            "publish date": "2016-02-10 08",
            "post link": "http://www.sffaudio.com/reading-short-and-deep-001-zero-hour-by-ray-bradbury",
            "file name": "rsd001ZeroHour.mp3",
            "hh:mm:ss": "0:34:05",
            "byte size": "32,972,064",
            "podcast participants": "Eric S. Rabkin and Jesse Willis",
            "book title": "Zero Hour",
            "book author": "Ray Bradbury",
            "genre type": "Story",
            "pdf link": "http://www.sffaudio.com/podcasts/ZeroHourByRayBradbury.pdf",
            "video link": "",
            "podcast description": "Zero Hour by Ray Bradbury",
            "publish_media_now": "yes",
            "itunes_pubDate": "Wed, 10 Feb 2016 08:00:00 PDT",
            "mp3_url": "http://www.canadianquotations.ca/rsd/rsd001ZeroHour.mp3",
            "byte_size": "32972064",
            "real_or_test": "real",
            "__v": 0
        }];


module.exports = props_array;